### PR TITLE
Another attempt at FreeBSD support

### PR DESCRIPTION
**Pull request by coreone**
This is a rewrite of my original PR on top of merging in changes from #33

### CODE REVIEW

**Comment by coreone** [comment]
Note: Do not merge yet.  Tests pass on my side, but still working on some issues.

**Comment by coreone** [comment]
@robinbowes FYI: I think the rubocop test is always going to fail now due to the warnings about using **should** instead of **is_expected.to**

**Comment by coreone** [comment]
@robinbowes this should be all set to go.  Additionally, if this is merged, #33 can probably be closed since I used those changes as the base for this PR.

**Comment by coreone** [comment]
Oh...and if this gets merged in, can we get a new release in the Forge as well?

Thanks!

**Comment by robinbowes** [comment]
OK, looks good. Does it need any documentation updates?

**Comment by coreone** [comment]
I think the documentation should be good.  Most of the changes were just to pull some hard-coded stuff out into variables so that FreeBSD differences could be accounted for.

**Comment by coreone** [comment]
@robinbowes just following up on this to see if we can merge it in.  Thanks!

**Comment by robinbowes** [comment]
Merged.

I'll try and get a release out soon - need to bottom out how to use modulesync to do it properly! :)

**Pull request merged**
