### PR TITLE
add official puppet 4 support

### PR DESCRIPTION
**Pull request by mmckinst**
* add official puppet 4 support
* drop puppet 2.7 support
* simplify the travis testing matrix- if there's no actual ruby code in the module, then there's no reason to test the module against all the different versions of ruby. just test against the versions of ruby officially supported by puppet:
* remove Gemfile.lock and add to .gitignore

### CODE REVIEW

**Comment by mmckinst** [comment]
some of this overlaps with pull request #16 but if the current code works with puppet 4.x, it would be great to see this merged and mentioned on puppetforge

**Comment by robinbowes** [comment]
Can you fix up the tests and I'll take a more detailed look at this?

**Comment by mmckinst** [comment]
@robinbowes tests now passing. I realized there's ruby code in the ruby templates so if you want to be on the super safe side, you might want to include all the versions of ruby like before

**Comment by robinbowes** [comment]
Yeah, can you put those back, except the 2.7.0 tests, and I'll merge this.

Have you done much testing with 4.x?

**Comment by mmckinst** [comment]
there we go, finally passing. I haven't done extensive testing with this module on puppet 4 yet, but will be doing tomorrow.

**Pull request merged**
