### PR TITLE
Allow config to be written via hiera

### PR DESCRIPTION
**Pull request by cwood**

### CODE REVIEW

**Comment by robinbowes** [comment]
Your change breaks the CI tests. Can you please investigate and fix?

**Comment by cwood** [comment]
Fixed the tests also ran into a dependency loop with both requireing and including the logrotate package.

**Comment by adamcstephens** [comment]
Big fan of this!

**Comment by cwood** [comment]
Any update if this can be merged in?

**Comment by adamgraves-choices** [comment]
+1

**Comment by robinbowes** [comment]
Can you please test the develop branch at 1b7bda1024c6865cff7eed6d334d4e6a7e187169 ?

I am looking into the dependency issue separately as I want to understand the problem fully before committing code.

**Comment by cwood** [comment]
Not sure why you couldnt just merge my code in but sure.

**Comment by robinbowes** [comment]
Because it combined several arbitrary changes (ie. the whitespace, and the removal of the "require => Class[...]").

I have added your other changes verbatim.

**Comment by robinbowes** [comment]
Pertinent code added manually and released in v1.2.8

**Pull request closed without merging**
