### PR TITLE
Adding basic support for FreeBSD

### PR DESCRIPTION
**Pull request by alxwr**
Hi,

I'm still working on this, but I wanted to get your feedback early. Please. :-)

Thanks for sharing this great piece of software!

Alex

### CODE REVIEW

**Comment by robinbowes** [comment]
Hi Alex,

I've not looked at your code at all yet, but a bare minimum for my accepting a PR is that the tests pass. Additionally, you should ensure that any new code has test coverage.

Also, please make sure you don't include trivial code changes like alignment, spacing, style changes in your main change - feel free to add those as separate PRs.

HTH,

Thanks for the contribution.

R.

**Comment by alxwr** [comment]
This helps a lot. :-)
I was going to provide passing and additional tests anyway. Just wanted to get your comment before I continue my work.

I'll test the changes on my FreeBSD and Debian systems before finishing the changes. This will take a few days. I'll be back. :-)

Alex

**Comment by robinbowes** [comment]
Hi Alex,

I had a quick look - generally, looks good!

I shall review your final submission more closely. :)

R.

**Comment by Wayneoween** [comment]
Can be closed because of #52 I think :+1:

**Comment by alxwr** [comment]
> Can be closed because of #52 I think :+1:

Indeed.

**Pull request closed without merging**
